server:
  port: 8085

spring:
  application:
    name: account-management-service
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:55722/account_management
    username: accountmanagement
    password: accountmanagement
  flyway:
    url: r2dbc:pool:postgresql://localhost:55722/account_management
    locations: classpath:db/migration